// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvNkloAqreLBVWL5yfB2Xk2UsH5sJoKQ8',
    appId: '1:817265633421:web:81d5a6cb21139cdbdcdac4',
    messagingSenderId: '817265633421',
    projectId: 'cheap-food-3dc88',
    authDomain: 'cheap-food-3dc88.firebaseapp.com',
    databaseURL: 'https://cheap-food-3dc88.firebaseio.com',
    storageBucket: 'cheap-food-3dc88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu3kJmESNw04m9gjvQrVwMMCxCW0Uk83I',
    appId: '1:817265633421:android:956a3a81a2db097adcdac4',
    messagingSenderId: '817265633421',
    projectId: 'cheap-food-3dc88',
    databaseURL: 'https://cheap-food-3dc88.firebaseio.com',
    storageBucket: 'cheap-food-3dc88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoBCFxgPeqH8MC6JQcnclkDwpCfajjHew',
    appId: '1:817265633421:ios:e080cebdcb888090dcdac4',
    messagingSenderId: '817265633421',
    projectId: 'cheap-food-3dc88',
    databaseURL: 'https://cheap-food-3dc88.firebaseio.com',
    storageBucket: 'cheap-food-3dc88.appspot.com',
    androidClientId: '817265633421-14cjb376fqg4fv1kbskb8ea94bej6lat.apps.googleusercontent.com',
    iosBundleId: 'com.abamadevelopers.pushApp',
  );
}
